export DB_HOST="localhost"
export DB_PORT="5432"
export DB_ADMIN_USER="mariadb"
export DBPASSWORD="xxxxx"
export AWS_ACCESS_KEY="xxxxx"
export AWS_SECRET_KEY="xxxxx"
export AWS_DEFAULT_REGION="ap-south-1"
export BUCKET_NAME="bucket/path"